### ISSUE TITLE
Replacing travis with github actions

### ISSUE THREAD

**Issue by klis87** [klis87/redux-requests#327]
I heard that new github actions are very nice. I didnt have time to read about it though, might be interesting thing to investigate and switch to potentially.

**Comment by strdr4605** [comment]
https://medium.com/better-programming/how-to-publish-a-javascript-package-to-npm-automatically-with-github-actions-1acde7b908d6

**Comment by strdr4605** [comment]
@klis87, I published a package [jump2header](https://github.com/strdr4605/jump2header) using GitHub actions and experience is nice.
The easiest is to start with the test + coverage workflow like:
https://github.com/strdr4605/jump2header/blob/master/.github/workflows/test.yml
I also added an action to release to npm with semantic release:
https://github.com/strdr4605/jump2header/blob/master/.github/workflows/release.yml
but the issue is with semantic-release as it does not support `v0.x.x`, so probably better to integrate release action after `v1` is ready.

**Comment by klis87** [comment]
@strdr4605 Thx for the links, I will take a look in a proper time!

**Comment by klis87** [comment]
Travis + lerna seems fine for now, so I am closing this, perhaps I will get back to it some day.
