### ISSUE TITLE
getData does not allow updating multiple reducers

### ISSUE THREAD

**Issue by burgalon** [klis87/redux-requests#333]
The example in https://github.com/klis87/redux-saga-requests/blob/master/examples/basic/src/store/actions.js#L11 seems to point to an issue with the new paradigm of queries and mutation without reducer (as initially discussed on email):

When fetching a post and comments together, you might want to store those comments on a separate reducer like FETCH_POST_COMMENTS, so that the objects in the redux match the server side schema, and that you can later call `updatePost` with the object from the redux which does not include comments. 
However with the `getData` approach, this does not seem to be possible as you can only update the query reducer you're currently in. This used to be possible with 0.26 where we would have multiple `requetReducer`s using the same action.type and reducing different aspects of the response.

To be clear this not a theoretic issue, but rather an issue I'm currently dealing with in the migration from 0.26 => 0.27 and currently solving with reselect selectors although doesn't feel ideal. 
Example of another use case of this: An endpoint might return two object types together and I would like those normalized and saved separately in different reducers as they do not depend on each other (i.e: caching, normalization logic, reset logic....)

**Comment by klis87** [comment]
@burgalon looking only at example you pasted, post and comments are stored together only because we wanted it to be, by using batch reuest (request as array of configs). You could easily have separate queries for post and for comments, which would store them independently.

> An endpoint might return two object types together and I would like those normalized and saved separately in different reducers as they do not depend on each other (i.e: caching, normalization logic, reset logic....)

This is an interesting topic, but I probably cannot imagine it completely. For instance re caching, if I have a `QUERY` which gets data consisting of 2 objects, lets pretend I want to cache 1 object and not another. How this could work if  cache is per query type and optionally per requestKey. Now in a place you dispatch `QUERY` again, how we could know that this query needs only cached object or also not cached object which would trigger a request? Do you have any examples how you imagine this could work?

Regarding your problem, indeed reselect is 1 nice idea. You can create as many selectors as you want based on `getQuery`. Each one could return part of data for the dependent query.

Regarding partial reset logic though, local mutations could update any data you want, for as many queries as you want within 1 action. Maybe thats what you need? https://github.com/klis87/redux-saga-requests#local-updates

**Comment by burgalon** [comment]
let's suppose I have an API 
```
GET /posts/:id
{
  id: 1
  title: 'title',
  body: '....',
  comments: [...]
```
and in the REDUX, I would like to normalize it and separate comments from the post. This will allow me later to call `updatePost` on the same object without the comments.

Is that a good example?

**Comment by klis87** [comment]
what do you mean by normalizing? this? https://github.com/klis87/redux-saga-requests#normalisation-arrow_up

this library supports normalisation out of the box, and updating an object as in readme is as simple as:

```js
const likeBooks = ids => ({
  type: 'LIKE_BOOKS',
  meta: {
    localData: ids.map(id => ({ id, liked: true })),
  },
})
```

Is this helpful?

**Comment by burgalon** [comment]
normalization in this context means saving each object type in its own namespace as recommended by redux guidelines, similar to a table in a database. i.e: comments separately from posts

**Comment by klis87** [comment]
so each object is stored only once, this is exactly what built-in normalisation does

**Comment by burgalon** [comment]
not just once... but also separately

Let's suppose the API is:
```json5
// GET /post/1

{
  posts: {
    "1": {
         id: 1,
         title: 'title',
         body: '....',
         author: {
            id: 1,
            name: 'John Doe'
         }
     }
  }
}
```

So instead of the redux looking like:
```
{
  posts: {
    1: {
         id: 1
         title: 'title',
         body: '....',
         author: {
            id: 1,
            name: 'John Doe'
         }
     }
  }
```

I would like it like:
```
{
  posts: {
    1: {
         id: 1
         title: 'title',
         body: '....',
       }
  },
  authors: {
         1: {
            id: 1,
            name: 'John Doe'
         }
  }
```

**Comment by klis87** [comment]
Yeah, this is what built-in normalisation does, objects with ids are stored in flat object, and queries only have reference to them, no data is stored more than once. See https://github.com/klis87/redux-saga-requests/tree/master/examples/normalisation and inspect what is inside reducer

**Comment by burgalon** [comment]
in our case we cannot easily (and currently prefer not to) use the redux-saga-requests normalization feature. For example, the `ids` are not unique across the app. We need to be able to normalize manually. Is that possible?

**Comment by klis87** [comment]
In theory yes, this library is very modular, you could always use your own reducers, which stores data, pending, error, and reacts for a given request type and its success, error and abort actions. But in reality, this is huge manual work, you need to track all relations, and here u have normalization like in Apollo, just automatic. But ofc if you need, custom reducers is the way to go.

**Comment by klis87** [comment]
@burgalon Closing, feel free to ask any more questions if needed
