### ISSUE TITLE
Promise `response.data` is transformed using `getData` without access to raw original data and response AxiosResponse object

### ISSUE THREAD

**Issue by burgalon** [klis87/redux-requests#334]
When migrating 0.26=>0.27 I noticed that the successAction.response.data is the transformed data after getData was applied.
1) The getData makes sense in the context of redux and normalization logic, however when calling a promisified action, I'd usually like to have the raw data.
2) Also for a reason I still do not completely understand the AxiosResponse object is not there, and the object includes only `data` attribute making it impossible to inspect headers and status code?

**Comment by klis87** [comment]
@burgalon see https://github.com/klis87/redux-saga-requests/issues/320

**Comment by klis87** [comment]
to sum up, I can resolve request promise only with response which is stored in reducer, otherwise for cached responses and SSR we could not recover raw responses

for now we store only data in reducer, but we could add more, like headers, statusCode

I have to use getData before resolving response for the very same reason - consistency,

In theory I could store original data too, but what about mutations together with cached query? Mutation would need to update both data and rawData, which would be very unpleasant. Now data is only one, single source of truth, no bugs, no synchronisation issues.

Hence this decision, if you want to store a data in a raw form, do not use getData to make this transformation, do it on selector level. Future version of this library will have helpers like mapQuery, mergeQueries and so on, but it is just normal reselect usage, one of the examples can be seen in readme.

**Comment by klis87** [comment]
Now response contains also `headers` and `status` for axios and fetch drivers, with custom driver any attr next to data is allowed
