### ISSUE TITLE
[Promise Driver] Action API

### ISSUE THREAD

**Issue by strdr4605** [klis87/redux-requests#339]
Now when I am looking at the action API for promise driver I think that 

```js
const fetchPhoto = id => ({
  type: FETCH_PHOTO,
  request: axios.get(`https://jsonplaceholder.typicode.com/photos/${id}`),
});
```
make more sense than

```js
const fetchPhoto = id => ({
  type: FETCH_PHOTO,
  request: {
    promise: axios.get(`https://jsonplaceholder.typicode.com/photos/${id}`),
  },
});
```
as request already means a promise, so maybe `{ promise: new Promise() }` is redundant.

**Comment by klis87** [comment]
I thought about the very same yesterday :) Especially that we could have other drivers, like observable etc, then we would have request.observable

only request is enough in those 2 cases because we will never pass anything else apart from promise itself. unless we will....

I thought also about some hook for promise library which could allow true requests cancellations

for now if you pass axios promise, really from redux perspective we support aborts, but xhr requests is actually not aborted, would be cool to somehow support that

**Comment by klis87** [comment]
I decided not to change it. We almost have version 1 and if for some reason we will add another config option next to promise, then we would need to make a breaking change again. Now it is flexible as we can put anything next to `request.promise`
