### ISSUE TITLE
Allow getData to return an error

### ISSUE THREAD

**Issue by ccapndave** [klis87/redux-requests#349]
When making a request for some JSON I would like to decode/transform it during the request.  `getData` is a neat place to do this, but the transformation can fail depending on the response, and I can't see a way to return an error from `getData`.

Is there a way to do this already, or would this be an additional feature?

**Comment by klis87** [comment]
@ccapndave can u explain why transformation could fail? shoudnt server reply with 400 status code if transformation would not be possible? btw, probably this is not what you need but server error can be transformed with either `meta.getError` or `onError` interceptor or `meta.onError`

**Comment by ccapndave** [comment]
So, I receive data of shape `A`, and I want to transform it into data of shape `B`.  If the data that arrived turns out not to be shape `A` then decoding is impossible and I want to mark the whole request as having failed for reasons of invalid data.

e.g. I expect the request to return an `array`, but it returns a `string` and so `getData` can't do its job.

**Comment by klis87** [comment]
so actually you would like to change success response into error response? so that for FETCH action FETCH_ERROR would be dispatched, not FETCH_SUCCESS?

**Comment by ccapndave** [comment]
Exactly!

**Comment by klis87** [comment]
currently there is no way to do it cleanly, but this is what i recommend:
- use onResponse or getData and if transformation if not possible, return like `error` or sth
- on reducer it will be still stored in `data` not in `error`, but you can for instance use selector to change that, like:
```js
import { createSelector } from 'reselect'
import { getQuerySelector } from '@redux-requests/core';

const myQuerySelector = createSelector(
  getQuerySelector('FETCH_STH'),
  query => ({
    ...query,
    data: query.data === 'error' ? null : query.data,
    error: query.data === 'error' ? 'error' : null,
  }),
)

```

Currently there is a way to recover from server error, like using onError to return data not rethrow error so that error is changed to success, but other way around is not possible.

In my opinion this would be like an escape hatch for not properly made API, but I also was hit by that, that I wanted sth to be error not success and for some reason backend developer was reluctant to change it. We would need to have another interceptor type, which would be called before onError and onSuccess, like onResponse, I will probably add this to todo list

**Comment by klis87** [comment]
Next interceptors will have `onResponse` which will be exactly for this purpose. `getData` will remain to be still only data transformation function, it already will be fired for a success
