### ISSUE TITLE
How to install the "load more" logic with normalization?

### ISSUE THREAD

**Issue by favger** [klis87/redux-requests#393]
I could not establish the "load more" system with this logic with my own efforts. Can someone who has solved it before give me a tip?

My Request Actions:
```
export const fetchConversations = (filter, options = {}) => ({
    type: FETCH_CONVERSATIONS,
    request: {
        method: "GET",
        url: URL_CONVERSATIONS,
        relativeParams: ['workspace'],
        params: {
            folder: "status-all",
            ...filter
        }
    },
    meta: {
        normalize: true
    }
});

export const updateConversation = (data, effectedProps) => ({
    type: UPDATE_CONVERSATION,
    request: {
        method: "POST",
        url: URL_CONVERSATIONS,
        relativeParams: ['workspace'],
        data: {
            conversation_id: data.id,
            ...effectedProps
        }
    },
    meta: {
        takeLatest: true,
        requestKey: data.id,
        optimisticData: { ...data, ...effectedProps },
        revertedData: data
    }
});
```

**Comment by klis87** [comment]
@favger tol level arrays you need to update manually, just by mutations, see https://redux-requests.klisiczynski.com/docs/tutorial/10-automatic-normalisation#normalisation-of-arrays

this is the same in apollo graphql for example, just it cannot be done automatically because library cannot know which arrays should be updated

perhaps in the future I will make it more declarative, but for now you need to just use mutations

**Comment by klis87** [comment]
```js
export const addConversation = (conversation) => ({
    type: ADD_CONVERSATION,
    request: {
        method: "POST",
        url: URL_CONVERSATIONS.ADD,
    },
    meta: {
        mutations: {
          [FETCH_CONVERSATIONS]: data => [...data, conversation],
       },
    }
});
```

Sth like that, probably update method would need to be adjusted, I don't know whether data is already array of conversations or not
