### ISSUE TITLE
What is the best way to store pagination and status information returned from Api?

### ISSUE THREAD

**Issue by favger** [klis87/redux-requests#396]
Example Api Response:
![ss-01](https://user-images.githubusercontent.com/25633595/98341652-3844b000-2020-11eb-8e95-6172f2c6f7da.png)

My agentDriver:
```
const agentDriver = requestConfig => {
    const abortSource = axios.CancelToken.source();

    const responsePromise = agent({ 
        cancelToken: abortSource.token, 
        ...requestConfig
    })
    .then(({ data: { data, ...rest }, headers, status }) => ({ 
        data: {
            results: data,
            ...rest,
        },
        headers,
        status
    }))
    .catch(error => {
        if (axios.isCancel(error)) {
            throw 'REQUEST_ABORTED';
        }
        
        throw error;
    });

    responsePromise.cancel = () => abortSource.cancel();
    return responsePromise;
};
```

**Comment by favger** [comment]
My bad practice:
![ss-03](https://user-images.githubusercontent.com/25633595/98346211-b441f680-2026-11eb-9cc1-9f9dc3eeec53.png)

**Comment by klis87** [comment]
what agentDriver does in comparison to axiosDriver? is this about transforming response? if yes, instead of writing own driver, you could just use onSuccess interceptor

you could also write axios driver, add your own then and so on with functional programming

Regarding paginated data and your getData, I can see that you merge everything by concatenation. Actually that would be my way of doing this for things like infinite scroll, load more and stuff like that.

But for paginated view, either just store current page and override it on page change (you probably show current page anyway)

... or, if you dont want to lose previous pages, you could just use meta.requestKey - https://redux-requests.klisiczynski.com/docs/tutorial/3-request-keys

and storing things like numberOfPages and so on you also can store in query.data

**Comment by favger** [comment]
@klis87 First of all, thank you very much, this statement really enlightened me.

Now I solve the problem as follows:
![ss-05](https://user-images.githubusercontent.com/25633595/98368290-2971f380-2048-11eb-9a75-e03273b32795.png)
![ss-06](https://user-images.githubusercontent.com/25633595/98368473-735ad980-2048-11eb-920c-3024ab6f476f.png)
![ss-07](https://user-images.githubusercontent.com/25633595/98368300-2bd44d80-2048-11eb-9339-2c2a889096e2.png)
![ss-08](https://user-images.githubusercontent.com/25633595/98368302-2d057a80-2048-11eb-9276-6f64ed6eb8b3.png)
![ss-09](https://user-images.githubusercontent.com/25633595/98368306-2d9e1100-2048-11eb-84b9-e1ac23d26d9a.png)

I tried to explain the solution as much as I could. I hope I have helped other people while solving this problem. If I cannot explain my solution incompletely or completely, be sorry, I am trying to improve myself in this subject.

**Comment by klis87** [comment]
@favger thx for your snippets! at some point I will add pagination/inf scrolling to guides. Closing for now!
