### ISSUE TITLE
is it possible to catch all request errors ?

### ISSUE THREAD

**Issue by sylvainbaronnet** [klis87/redux-requests#431]
Hello,

Is there a way to catch all requests errors for example with redux saga ? Other than using `error(action.toString())` for all request actions ? 

My use case is to watch for auth token expiration error for all request.

I use axios drive so maybe I could do it in its config directly, but I'd prefer using saga, so I can dispatch some action when it happens

**Comment by sylvainbaronnet** [comment]
I have all my actions in an object already so I was able to work out something : 

```
export function* saga() {
  const actionTypesError = [];
  keys(api).forEach(a => {
    actionTypesError.push(error(api[a].toString()))
  })
  yield takeLatest(actionTypesError, onRequestError);
}
```

But would be nice if there was an easier way

**Comment by klis87** [comment]
@sylvainbaronnet use `onError` interceptor, in the docs you can see some ideas for token refreshment - https://redux-requests.klisiczynski.com/docs/tutorial/6-interceptors#onerror Please read the whole stuff, as later you will see some ideas to avoid potential endless loops etc

By redux saga alone you cannot catch errors, because redux-saga is side effect library, it doesnt have power to intercept request, sagas are run after reducers are already hit

**Comment by klis87** [comment]
You could listen to all errors by using https://redux-requests.klisiczynski.com/docs/api-reference/is-response-action , and then checking suffix, but again, as side-effect to do something on error, but only `onError` interceptor could catch error, fire another request and replacing error response with success one

**Comment by sylvainbaronnet** [comment]
Thanks that's super useful!

Great lib, thanks a lot

**Comment by klis87** [comment]
Glad that it is helpful! Can we close it then? If not, don't hesitate to ask further questions. Actually you touched important topic about interceptors, see https://github.com/klis87/redux-requests/issues/397 if you are interested about potential interceptor changes

**Comment by sylvainbaronnet** [comment]
It's good I can close it, thanks again.

I'll try to check potential changes when I have time
