### ISSUE TITLE
Lazy loading (or pagination on scroll)

### ISSUE THREAD

**Issue by BigBadAlien** [klis87/redux-requests#438]
Does the library have an approach to implement lazy loading? I haven't found it in the sources or examples.

For example

```
GET /book/list/199?page_size=10&page=1
```

and on

```
GET /book/list/199?page_size=10&page=2
```

to concatenate both arrays. Any ideas? Otherwise, I would suggest adding the feature

Thanks

**Comment by klis87** [comment]
@BigBadAlien yes, you can concatenate `data` with action.meta.getData , which has access both to previous and current data, see https://redux-requests.klisiczynski.com/docs/api-reference/request-action#getdata-data-currentdata--transformeddata

**Comment by BigBadAlien** [comment]
Indeed, it's enough. Thanks!

**Comment by klis87** [comment]
@BigBadAlien cool. Actually I am going to make some recipies in the docs in the future, like lazy loading, pagination and more. This library doesn't have API to cover those cases "by name", but it is flexible to cover them all with a proper meta attributes' combination (at least I hope so). Do you have some more ideas for recipies which could be helpful for this library users?

**Comment by BigBadAlien** [comment]
Thanks for the lib. Really helpful to use it for common cases and apply Sagas if something more complex required.

> Do you have some more ideas for recipies which could be helpful for this library users?
Yeah, created https://github.com/klis87/redux-requests/discussions/442

I'll close the topic for now, since resolved by [getData](https://redux-requests.klisiczynski.com/docs/api-reference/request-action#getdata-data-currentdata--transformeddata)

**Comment by klis87** [comment]
> Thanks for the lib. Really helpful to use it for common cases and apply Sagas if something more complex required.

Interestingly, I don't know you know, but this library started as ... `redux-saga-requests` :) so it was just a saga addon, only later rewritten to pure redux so that it could be used not only with sagas. At the same time I actually stopped using sagas, as this lib + `redux-first-router` is enough for all the cases I encounter in my current apps.

**Comment by BigBadAlien** [comment]
@klis87 Yes, I'm acquainted with the first saga-based version. Yeah, I use sagas to handle external events not just requests and it's pretty difficult to avoid sagas for such cases

**Comment by klis87** [comment]
@BigBadAlien I am wondering what external events you mean, I am asking as requests pattern can be used/or maybe even abused for more cases. In the nearest time I am going to experiment with using this lib for even local state. Why? Because then you could achieve difficult tasks, like offline cache (will be added soon), normalisation and so on as easily as for "remote state", for free, in the very same, consistent way.

 Also, recently there were added subscriptions, which perhaps could be extended to other event types, not only for websocket messages.

**Comment by BigBadAlien** [comment]
> I am wondering what external events you mean
Like sockets or any other event-based data transport

Cool, looking forward to the changelog

**Comment by BigBadAlien** [comment]
> Also, recently there were added subscriptions, which perhaps could be extended to other event types, not only for websocket messages.

Can be useful, thanks! I'll take a look into it. Btw. Created a topic https://github.com/klis87/redux-requests/discussions/450

**Comment by klis87** [comment]
Cool! I pointed you some references to subscriptions. Wondering whether they will solve your use case!
